fast-aircraft-design/FAST-OAD

src/fastoad/io/xml/resources/legacy1.txt
src/fastoad/openmdao/variables.py
tests/integration_tests/oad_process/data/CeRAS01_legacy.xml

Added an input needed for the non-regression test to work on platforms that do not have XFOIL.
Also changed `VariableList.from_problem()` so that non-promoted variables are excluded by default. Otherwise, non-promoted variables get written in XML files using their absolute name.

Non regression fix

---

.github/workflows/tests.yml
docs/conf.py
src/fastoad/cmd/resources/fastoad.toml
src/fastoad/exceptions.py
src/fastoad/models/performances/breguet.py
src/fastoad/models/performances/tests/test_breguet.py
src/fastoad/models/propulsion/__init__.py
src/fastoad/models/propulsion/engine.py
src/fastoad/models/propulsion/fuel_engine/rubber_engine/__init__.py
src/fastoad/models/propulsion/fuel_engine/rubber_engine/exceptions.py
src/fastoad/models/propulsion/fuel_engine/rubber_engine/openmdao.py
src/fastoad/models/propulsion/fuel_engine/rubber_engine/rubber_engine.py
src/fastoad/models/propulsion/fuel_engine/rubber_engine/tests/test_openmdao_engine.py
src/fastoad/module_management/constants.py
src/fastoad/module_management/exceptions.py
src/fastoad/module_management/service_registry.py
src/fastoad/openmdao/validity_checker.py
src/fastoad/register.py
tests/integration_tests/oad_process/data/oad_process.toml
tests/testing_utilities.py

This PR reworks the engine model definition for preparing the upcoming development of a time-dependent performance module.
The engine model can now be put in a wrapper that should ease its usage in an OpenMDAO component and allow easy switching between propulsion models.
Additionally, Sphinx settings have been changed so that a class documentation is now the concatenation of the class docstring and the `__init__` docstring. This allows to put docstrings in `__init__` so we can get PEP257-compliant.

Engine rework

---

.github/workflows/tests.yml
poetry.lock
pyproject.toml
src/fastoad/cmd/api.py
src/fastoad/cmd/fast.py
src/fastoad/cmd/tests/test_api.py

A fix was needed for compatibility with wop v1.9.
The missing depth argument has been added.
Besides, wop 1.9 does not crash anymore if `xfoil` option is True (was crashing because of the connection of non promoted variables). Thank you @relf 😉 
v1.9 is now set as requirement for FAST-OAD.

updated for wop 1.9

---

.github/workflows/watchman_tests.yml

The added workflow will run tests with an up-to-date production environment instead
of the locked one.
It will warn developers if the update of a dependency broke something.

Added "watchman" tests

---

poetry.lock
pyproject.toml
src/fastoad/models/weight/mass_breakdown/mass_breakdown.py
src/fastoad/openmdao/variables.py

This PR enables to restore compatibility with the lastest version of OpenMDAO 3.1.1.
The main changes are:
- New usage of IndepVarComp since it now inherits from ExplicitComponent and no more has ._indep and ._indep_external private attributes 
- New usage of AddSusbtractComp to avoid a bug in OM when __init__() calls add_equation()

Openmdao 3.1.1 compatibility

---

CHANGELOG.rst

Release of version 0.3.1-beta
- Changed dependency requirement to have latest OpenMDAO version.
- Adapted the FAST-OAD code to handle this latest version.

Updated change log

---

CHANGELOG.rst

Due to a tag error, the 0.4.1b release is the same as the 0.4.0b.
So we make a [0.4.2b](https://github.com/fast-aircraft-design/FAST-OAD/releases/tag/untagged-a3cdffdf8b6655e03aa5) and remove the 0.4.1b from history.

release v0.4.2b because v0.4.1b is not what is should be.

---

src/fastoad/cmd/api.py
src/fastoad/models/propulsion/fuel_propulsion/rubber_engine/openmdao.py
src/fastoad/module_management/openmdao_system_registry.py
src/fastoad/module_management/service_registry.py

Since the new wrapper system for propulsion models, the registered wrapper were not listed when asking for system list. This is fixed by this PR.
The `RegisterService` class has got a bit larger and begins to smell like `OpenMDAOSystemRegistry` class. This is left as is for now, but a future PR may put that in order.

Now list_systems() also lists propulsion wrappers.

---

CHANGELOG.rst
src/fastoad/openmdao/variables.py

Numerous deprecation warnings were displayed in notebooks.
This is now fixed and a new release is proposed:
https://github.com/fast-aircraft-design/FAST-OAD/releases/tag/untagged-78ed6ca7419acbdfea21

Release 0.5.1 beta

---

src/fastoad/models/aerodynamics/external/xfoil/tests/test_xfoil.py
src/fastoad/models/aerodynamics/external/xfoil/xfoil_polar.py

XFOIL input file was badly generated if user tmp folder path was containing "RE".
Fixes #204.

Bug fix in generation of XFOIL input file

---

src/fastoad/cmd/api.py
src/fastoad/models/weight/cg/cg_components/update_mlg.py

This PR proposes minor changes:
- the computation time is now estimated using time() instead of process_time as this last method was providing under-estimated computation times when compared to user-side time
- the estimation of the main landing gear center of gravity now uses an ExplicitComponent instead of an ImplicitComponent + Group + Newton solver

Main landing gear

---

src/fastoad/models/aerodynamics/components/cd_compressibility.py
src/fastoad/models/aerodynamics/components/tests/test_components.py
src/fastoad/models/aerodynamics/tests/test_aerodynamics.py
src/fastoad/notebooks/tutorial/data/CeRAS01_baseline.xml
src/fastoad/openmdao/resources/variable_descriptions.txt
tests/integration_tests/oad_process/data/CeRAS01_legacy_breguet_result.xml
tests/integration_tests/oad_process/data/CeRAS01_legacy_mission_result.xml
tests/integration_tests/oad_process/test_oad_process.py

This PR fixes computation of compressibility drag, because only half of the model from SUPAERO course was implemented, resulting in complete negation of effect of sweep angle and thickness ratio on the compressibility drag.
But fixing the formula led to increasing the compressibility drag for CeRAS case. To keep current results (until we go through a thorough validation process), the change is balanced by reducing induced drag with the coefficient for winglet effect.
Nevertheless, even with this fix, compressibility drag of modern aircraft may still be overestimated by the model, so the variable `tuning:aerodynamics:aircraft:cruise:CD:compressibility:ceiling` has been added to cap the model result. Even with the default, very large, value, it allows to give better looking polar plots …

Fix compressibility drag

---

src/fastoad/openmdao/variables.py

Variables from _auto_ivc are no more in outputs from VariableList.from_problem, unless they are asked for.
Fixes #225

Avoiding to have _auto_ivc variables in list_variables output

---

src/fastoad/cmd/api.py
src/fastoad/cmd/tests/test_api.py
src/fastoad/utils/postprocessing/analysis_and_plots.py

Small PR to integrate two minor post-processing changes:
- The table produced by VariableViewer cannot be included in an HTML export of a notebook. Therefore api.variable_viewer() has been updated to propose a simpler table that can be exported in a HTML document. Default behavior is still that the VariableViewer is displayed.
- Plot of wing planform now displays X values with nose position as reference, which is more as one could expect.

Postprocessing minor changes

---

src/fastoad/models/aerodynamics/components/cd_compressibility.py
src/fastoad/models/aerodynamics/components/tests/test_components.py
src/fastoad/models/aerodynamics/tests/test_aerodynamics.py

As we know, model for compressibility drag is outdated, but until we have a better one, some tuning will do. The solution that only capped the compressibility drag was not satisfactory, as it naturally lead to unphysical evolutions. It has been kept to avoid having billion drag counts at high CL values, but a better tuning would be to move the "characteristic Mach" that drives the starting point of buffet.
Therfore:
"ceiling" is now "max_value" and should be used only to avoid CD to reach thousands or millions. Its default value is increased to 0.5.
"characteristic_mach_increment" can now be used to move the divergence to higher or lower Mach numbers

Added tuner parameter in computation of compressibility

---

src/fastoad/io/configuration/configuration.py
src/fastoad/io/configuration/exceptions.py
src/fastoad/io/configuration/tests/data/nan_inputs.xml
src/fastoad/io/configuration/tests/data/ref_inputs.xml
src/fastoad/io/configuration/tests/test_configuration.py
src/fastoad/openmdao/problem.py
src/fastoad/openmdao/utils.py

This PR makes FAST-OAD raise an error when the read inputs of a problem contain one or more NaN values, which fixes #241.
Also, the behavior has changed concerning input data that are not expected by the process:
- Until now, the OpenMDAO problem was fed with all variables from provided input data file:
1) if a variable was in input data file but was not part of the process, it was added to the input IVC with no more consequence (except possibly a slight performance loss...)
2) but if a variable was in input data file and was an output somewhere in the process, then it made OpenMDAO rightly raise an error about having twice the same output.
- With this PR, unneeded variables are ignored when reading input file, but stored to be written later in output file without having been part of the …

Check NaN values before computation

---

src/fastoad/cmd/api.py
src/fastoad/cmd/tests/test_api.py

This PR is a work around for using `api.write_n2()`  introduced by openmdao 3.7 `om.n2()` display mecanism when using file absolute paths in Jupyter notebooks.
Later, we should probably use directly openmdao's `om.n2()` for displaying the n2 in Jupyter notebooks.
Fixes #280.

Issue 280 n2 rendering

---

.github/workflows/tests.yml
.github/workflows/watchman_tests.yml

This PR modifies the tests workflow so they run only when changes are to software code, tests, or dependencies.
Also, tag creation do not trigger test workflows anymore.
> Here you may consider the PR approval as a simple read confirmation.

Limitation of test workflow triggering

---

CHANGELOG.rst
src/fastoad/__init__.py

New release to integrate the workaround for #306.
draft release: https://github.com/fast-aircraft-design/FAST-OAD/releases/tag/untagged-401c159ae5382c940841

Release v1.0.2

---

src/fastoad/cmd/api.py
src/fastoad/cmd/tests/test_api.py
src/fastoad/io/configuration/configuration.py
src/fastoad/io/variable_io.py

This PR solves #328.
The `DataFile` class, now used in `generate_inputs` was intended to load the content of a data file if it existed.
The class constructor has been modified to allow the data not to be loaded if necessary.

Fix overwrite of input file

---

src/fastoad/cmd/api.py
src/fastoad/io/configuration/configuration.py
src/fastoad/io/configuration/resources/configuration.json
src/fastoad/io/configuration/tests/data/valid_sellar.yml

This PR closes #324.
Unknown keys are now accepted in the configuration file (at root level).
To keep being informative about possible typos, a warning is issued for each found unknown key.

Allowing "useless" sections in configuration file

---

src/fastoad/openmdao/tests/test_variables.py
src/fastoad/openmdao/variables.py

This PR fixes #334 (partly solved by #332) where some variables are tagged as inputs instead of outputs when using `VariableList.from_problem()`.
To fix this, `VariableList.from_problem()` was modified to handle the effect of using `connect()` with local inputs and promoted outputs. This behaviour can be observed when using `list_variables()` or the `variable_viewer()`.
However, `generate_inputs()` works fine and gives the correct input list because it uses `_utils.get_unconnected_input_names()`. This brings up the fact that `VariableList.from_problem()` is too complicated for what we really need it to do and should deserve a rework in a later PR.

Issue 334 - local inputs connected to promoted variables

---

.github/workflows/tests.yml
.github/workflows/watchman_tests.yml

Currently, GitHub workflows for tests are triggered only when source code is changed, to avoid some useless runs of actions.
But it happened to prevent tests to be run when merging a release branch that modifies only the change log. It results in a commit on master branch that dis not send its coverage data, so that next branches cannot be evaluated by Codecov, since it has no base for comparison.
Therefore, following changes are done in GitHub workflows for tests:
- Tried to force tests to run, whatever the changed files, when some pull request events happen. We will probably have to see the real effect on the long run...
- As notebook tests have become very long, made that notebook tests are triggered only on master commits, pull requests, or when `[test nb]` is in the commit message.

Adjustment of test triggering in GitHub workflows

---

.github/workflows/tests.yml
.github/workflows/watchman_tests.yml

Avoiding to launch tests when only non-python files were changed looked attractive, but it has some drawbacks:
- if a commit on the master branch has not been tested, it has no coverage report for Codecov. And then, a branch
that starts from that commit will not have a relevant base for coverage comparison.
- if the last commit of a branch has not been tested, the associated PR will not show any test-related check.
However, we keep avoiding launching tests on new tags, and we keep doing sparingly the time-consuming notebook tests.
Also, python 3.9 runners have been added to the test matrix, and watchman tests are now launched with Python 3.9.

Test workflows are now launched whatever the changed files are.

---

src/fastoad/models/performances/mission/mission_definition/tests/data/mission.yml
src/fastoad/models/performances/mission/openmdao/mission.py
src/fastoad/models/performances/mission/openmdao/resources/sizing_mission.yml
src/fastoad/models/performances/mission/segments/taxi.py
src/fastoad/models/performances/mission/segments/tests/test_segments.py
src/fastoad/notebooks/01_tutorial/data/CeRAS01_baseline.xml
tests/integration_tests/oad_process/test_oad_process.py

This PR fixes #311.
It corrects a far too large assessment of the distance during the taxi-in segment. This was due to the fact that the last FlightPoint used was from the holding phase so a quite high mach applied to the duration of the taxi-in segment.
Now taxi segments have a distance which is equal to `0` since we now set the `true_airspeed` parameter of this segment to `0`. Changing the `true_airspeed` has lead to a lower `sfc` hence different fuel mass in the taxi-in segment. This change in mass has spread in the different loops which required an update of the variable values (MTOW, wing_area...) in the tests.

Issue 311 - Incorrect taxi-in distance

---

src/fastoad/gui/optimization_viewer.py

This PR fixes #372.
Now the `optimization_viewer` does not modify the output file when clicking the `Save` button.
Also, the `Value` cells have been disabled and thus cannot be modified anymore.
Finally, in the absence of an output file, the `optimization_viewer` will display `-` in the `Value` cells instead of default values found in the models.

Issue 372 optimization viewer modifying output file

---

CHANGELOG.rst

Release to bring back compatibility with OpenMDAO 3.10.
Draft release here: https://github.com/fast-aircraft-design/FAST-OAD/releases/tag/untagged-c7bcf8b0a8f80f231888

Release 1.0.5

---

src/fastoad/cmd/api.py
src/fastoad/cmd/fast.py
src/fastoad/cmd/tests/test_api.py

This PR closes #365. It provides the possiblity to use `list_modules()` without providing a configuration file in the presence of custom modules. 
Now (but this is open to discussion), the source used for `list_modules()` can be:
- the path of a configuration file
- the path of a folder containing the custom modules
- a list of folder paths that each contain custom modules

Issue 365 listing custom modules

---

src/fastoad/models/aerodynamics/components/high_lift_aero.py
src/fastoad/models/aerodynamics/components/tests/test_components.py
src/fastoad/models/propulsion/fuel_propulsion/rubber_engine/openmdao.py
src/fastoad/models/propulsion/fuel_propulsion/rubber_engine/rubber_engine.py
src/fastoad/models/propulsion/fuel_propulsion/rubber_engine/tests/test_openmdao_engine.py
src/fastoad/models/variable_descriptions.txt

This little PR adds changes to aerodynamic and rubber engine models: 
- The high lift aerodynamic model has been updated adding two tuning parameters to correct the additional lift and drag due to flaps to take into account multiple slotted flaps. 
- The rubber engine model has been updated adding two tuning parameters to correct SFC at sea level (SL) and at 43000ft (ceiling for most of commercial aircraft). Between SL and 43000 the correction is linearly interpolated and saturations are introduced below SL and above 43000ft.

Aero engine models update

---

src/fastoad/cmd/tests/data/short_inputs.xml
src/fastoad/models/geometry/geom_components/wing/components/compute_l1_l4.py
src/fastoad/models/geometry/geom_components/wing/components/compute_l2_l3.py
src/fastoad/models/geometry/tests/data/geometry_inputs_full.xml
src/fastoad/models/geometry/tests/test_geometry_geom_comps.py
src/fastoad/models/variable_descriptions.txt
src/fastoad/models/weight/cg/tests/data/cg_inputs.xml
src/fastoad/notebooks/01_tutorial/data/CeRAS01_baseline.xml
src/fastoad/notebooks/02_CeRAS_case_study/data/CeRAS_data_for_plots.xml
src/fastoad/notebooks/02_CeRAS_case_study/data/CeRAS_reference_data.xml
tests/integration_tests/oad_process/data/CeRAS01_legacy.xml
tests/integration_tests/oad_process/data/CeRAS01_legacy_breguet_result.xml
tests/integration_tests/oad_process/data/CeRAS01_legacy_mission_result.xml

This PR resolve #363.
The "data:geometry:wing:taper_ratio" variable used as an input so far does not correspond to the classical definition of wing taper ratio. Therefore, not to modify all the geometry definition of the wing, the input variable was changed to "data:geoemetry:wing:virtual_taper_ratio" and an ouput "data:geometry:wing:taper_ratio" was created with the proper definition.

Issue 363 taper ratio

---

CHANGELOG.rst
src/fastoad/cmd/fast.py

This PR fixes #394 making list_modules functional again using CLI.
This is the opportunity to do a patch release 1.1.1 (https://github.com/fast-aircraft-design/FAST-OAD/releases/untagged-7eeb0813b780611d787d) to include this bug correction.

Issue 394 list modules + Release 1.1.1

---

CHANGELOG.rst
src/fastoad/models/performances/mission/segments/base.py
src/fastoad/models/performances/mission/segments/cruise.py
src/fastoad/models/performances/mission/segments/tests/test_segments.py
tests/integration_tests/oad_process/test_oad_process.py

This PR fixes #396. The bug was forcing engine setting to climb if an altitude target was set for the cruise segment.
Additional checks have been put in related tests.
It also proposes release of version 1.1.2: https://github.com/fast-aircraft-design/FAST-OAD/releases/untagged-02fe8a16462bc2c95738

Mission computation: engine setting in cruise

---

docs/requirements.txt
poetry.lock
pyproject.toml
src/fastoad/model_base/atmosphere.py
src/fastoad/models/aerodynamics/aerodynamics_landing.py
src/fastoad/models/aerodynamics/components/compute_reynolds.py
src/fastoad/models/aerodynamics/components/tests/test_components.py
src/fastoad/models/handling_qualities/tail_sizing/compute_ht_area.py
src/fastoad/models/performances/mission/segments/altitude_change.py
src/fastoad/models/performances/mission/segments/base.py
src/fastoad/models/propulsion/fuel_propulsion/rubber_engine/constants.py
src/fastoad/models/propulsion/fuel_propulsion/rubber_engine/rubber_engine.py
src/fastoad/models/propulsion/fuel_propulsion/rubber_engine/tests/test_rubber_engine.py
src/fastoad/models/weight/mass_breakdown/cs25.py

With this PR, FAST-OAD now uses [stdatm ](https://pypi.org/project/stdatm/)package to simulate Standard Atmosphere.
Atmosphere classes in FAST-OAD are set as deprecated.

Now using stdatm package

---

src/fastoad/cmd/api.py
src/fastoad/cmd/fast.py
src/fastoad/cmd/tests/data/ref_list_variables_with_variable_descriptions_format.txt
src/fastoad/cmd/tests/test_api.py

This small PR aims at providing the possibility to generate a file such as the `variable_descriptions.txt` by activating an option in `api.list_variables(variable_descriptions_format=True)`.
This is particularly useful when building a new (large) custom module from scratch.

Generate variable descriptions

---

.github/workflows/build_release.yml
CHANGELOG.rst
docs/requirements.txt
poetry.lock
pyproject.toml
src/fastoad/cmd/fast.py
src/fastoad/model_base/atmosphere.py
src/fastoad/openmdao/variables.py

Release 1.2.0 has been done unvolontarily due to a bad timing when pressing return 😞 
The publish action has been too fast. Maybe I should see if I can add a delay in the workflow 😅 ... or I should look at means for better automation of this process...
So I yanked release 1.2.0 on PyPI and doing this version 1.2.1 properly.
Besides the change log, I modified the informative text after creation of notebooks so that users launch jupyter lab instead of jupyter notebooks.
https://github.com/fast-aircraft-design/FAST-OAD/releases/edit/untagged-16fffb777ca80907d44f

Release v1.2.1

---

.github/workflows/tests.yml
src/conftest.py
src/fastoad/cmd/cli.py
src/fastoad/module_management/_plugins.py
src/fastoad/module_management/exceptions.py
src/fastoad/module_management/tests/test_plugins.py

Minor change to amend PR #409. With no plugin installed, it is possible to have no configuration file available, and that case was not handled correctly.
Additionally, I take the occasion to try a new settings for cache in GitHub actions. Let's see if it behaves better on Windows now.

Fixed case with no configuration file available

---

.github/workflows/build_for_Binder.yml
.github/workflows/build_release.yml
.github/workflows/watchman_tests.yml
CHANGELOG.rst
README.md
pyproject.toml
src/fastoad/module_management/_plugins.py

Draft release: https://github.com/fast-aircraft-design/FAST-OAD/releases/tag/untagged-b92c8e0eee264465d34a
This PR officializes the new plugin system and the separation of CS25 models.
FAST-OAD is declared dependent of FAST-OAD-CS25 to ensure both will be installed by pip. Additionally, build/publish workflow has been modified so that it should publish also a release of FAST-OAD-core that does not require FAST-OAD-CS25 (if it does not work, I'll do it manually 😅).

Release v1.3.0

---

CHANGELOG.rst
README.md

Maintenance release, especially for allowing usage of StdAtm 0.2.
Draft release here: https://github.com/fast-aircraft-design/FAST-OAD/releases/tag/untagged-91e6f3abfdde6aa2e7a0

Release v1.3.1

---

CHANGELOG.rst
src/fastoad/openmdao/problem.py
src/fastoad/openmdao/tests/test_problem.py

Resolves #427.
OpenMDAO 3.17 modifies the signature of `om.Problem.set_val()`, which caused FAST-OAD 1.3.1 to crash at problem initialization.
Also, the unit test for `FASTOADProblem.write_outputs()` needed a small fix.

Hot fix release 1.3.2 :  compatibility with OpenMDAO 3.17

---

.pre-commit-config.yaml
docs/requirements.txt
poetry.lock
pyproject.toml

This small PR adds [nbstripout](https://github.com/kynan/nbstripout) to dependencies and pre-commit hooks.
This way notebook outputs are deleted when notebooks are committed. 
I tested the pre-commit and it seems to work fine.
Once approved and merged I will do the same modifications for the [CS_25](https://github.com/fast-aircraft-design/FAST-OAD_CS25) repository which contains more notebooks.

Added nbstripout to dependencies and pre-commit

---

.github/workflows/build_release.yml
.github/workflows/tests.yml
.github/workflows/watchman_tests.yml
docs/documentation/data.xml
docs/documentation/variables.rst
src/fastoad/io/tests/test_data_file.py
src/fastoad/io/variable_io.py
src/fastoad/openmdao/variables/variable_list.py

This PR aims at easing a bit the usage of DataFile class:
- fixes #421 and #429
- allows instantiating a DataFile with no argument or from list of a Variable instances
- adds the `save_as()` method
- adds a documentation section about usage of DataFile (preview [here](https://fast-oad.readthedocs.io/en/datafile-enhancement/documentation/variables.html#fast-oad-api))
BTW, I changed a bit the GitHub workflows to take advantage of the cache management of the `setup-python` action, that works for Poetry (bye bye `actions/cache`). I used this branch as a sandbox to test it.
Finally, since CodeClimate was nagging me with a "two many nested control flows" in the dreaded `VariableList.from_problem()` method (just because I slightly modified it to fix issue 421), I decided to comply by simply …

Datafile enhancement

---

src/fastoad/io/configuration/tests/data/valid_sellar_with_indep.toml
src/fastoad/io/configuration/tests/test_configuration.py
src/fastoad/openmdao/tests/test_variables.py
src/fastoad/openmdao/variables/variable_list.py

This PR resolves #436. 
The issue was that `IndepVarComp` connections were ignored when analyzing connections for sorting inputs and outputs.
Thus, the variables to which they were connected were still considered as inputs and therefore added to the generated input file.

Issue 436 - configuration file connections with indepvarcomp

---

.github/workflows/tests.yml
poetry.lock
pyproject.toml
src/fastoad/openmdao/_utils.py
src/fastoad/openmdao/problem.py
src/fastoad/openmdao/variables/variable_list.py

This PR fixes #441.
It ensures that the OpenMDAO MPI communicators are removed from Problem instances before doing a deepcopy operation.
For good measure, our GitHub test workflow now runs with MPI capabilities installed.

Fix for crash in multiprocessing environment

---

.github/workflows/tests.yml
src/fastoad/module_management/_bundle_loader.py
src/fastoad/openmdao/problem.py
tests/memory_tests/__init__.py
tests/memory_tests/data/CeRAS01.xml
tests/memory_tests/data/oad_process.yml
tests/memory_tests/test_multiple_runs.py

OpenMDAO objects were persisting in RAM after setup or run operations.
This could be a problem when running multiple computations in the same Python session: memory consumption was continuously raising, and computation time was increasing.
This was due to iPOPO instantiating OpenMDAO components, but never releasing them, since we did not ask to.
This PR solves this problem in a somehow rough way, but it apparently works fine.

Memory fix

---

docs/documentation/custom_modules/add_submodels.rst
src/fastoad/io/configuration/configuration.py
src/fastoad/module_management/service_registry.py
src/fastoad/module_management/tests/test_register_submodel.py

Solves #440.
This PR ensures that all sub-models are reactivated before processing sub-models from the configuration file.
Some modifications have also been done to the [documentation](https://fast-oad.readthedocs.io/en/issue-440_reset-null-submodels/documentation/custom_modules/add_submodels.html).

Issue 440 reset null submodels

---

src/fastoad/openmdao/problem.py

Solves #448.
Quick fix to avoid uncontrolled generation of `reports` folder with OpenMDAO 3.17+.
Solution is to deactivate entirely this feature, unless environment variable OPENMDAO_REPORTS is set. I suggest we see later if we add a control for it in the configuration file.
No test is implemented for this modification, since I prefer to keep our Poetry environment with the old OpenMDAO 3.10 (yet I tested it "manually", of course)). At least, watchman tests will ensure the change does not cause any crash.

Deactivated automatic reports.

---

src/fastoad/gui/analysis_and_plots.py
src/fastoad/gui/tests/test_analysis_and_plots.py

Fixes #450.
The number of datasets in mass breakdown bar plot was limited to 5 due to an incorrect indexing in the list `plotly.colors.DEFAULT_PLOTLY_COLORS` (which contains 10 items).
Besides, colors in mass breakdown plot were inconsistent with colors in other plots (geometry, polar). The color list for mass breakdown bar plot is now close to the one used in other plots.

Now allowing more than 5 datasets in mass breakdown bar plot

---

CHANGELOG.rst
src/fastoad/models/performances/mission/openmdao/resources/sizing_breguet.yml
src/fastoad/models/performances/mission/openmdao/resources/sizing_mission.yml
src/fastoad/models/performances/mission/openmdao/tests/test_sizing_breguet.py
src/fastoad/models/performances/mission/openmdao/tests/test_sizing_mission.py

In version 1.4.0, bundled missions now require the takeoff duration as mandatory input, which was not the case before.
This is fixed now.

Fixed backward compatibility of bundled missions

---

src/fastoad/io/configuration/configuration.py
src/fastoad/io/configuration/tests/data/ref_inputs_with_nan.xml
src/fastoad/io/configuration/tests/test_configuration.py
src/fastoad/openmdao/problem.py

This PR closes #278 by adding a warning when NaN values are encountered in the source file of `generate_inputs`.

Added warning for nan values when generating inputs

---

poetry.lock
pyproject.toml
release/pyproject.toml

Notebooks in `fast-oad-cs25` plugin have been adapted to the slight changes in mission model from FAST-OAD 1.4. Installation of version 0.1.4 of `fast-oad-cs25` requires `fast-oad-core` 1.4.1, which is Ok.
But currently, updating `fast-oad` does not trigger the update of fast-oad-cs25, hence CS25 notebooks have some problems in mass breakdown plots.
This is fixed by current PR by making `fast-oad` requiring at least `fast-oad-cs25` 0.1.4.

Updated dependency to FAST-OAD_CS25

---

docs/conf.py
docs/documentation/mission_module/extensibility/adding_segments.rst
docs/documentation/mission_module/mission_file/index.rst
docs/documentation/mission_module/mission_file/mission_file.rst
docs/documentation/mission_module/mission_file/segments.rst
docs/documentation/mission_module/mission_file/setting_values.rst
docs/documentation/usage.rst
src/fastoad/models/performances/mission/openmdao/tests/data/test_mission_takeoff.yml
src/fastoad/models/performances/mission/polar_modifier.py

This PR updates Sphinx doc regarding recent takeoff additions.
Preview available here : https://fast-oad.readthedocs.io/en/takeoff-documentation/documentation/mission_module/mission_file/segments.html
Also, some fixes in documentation have been added.

Takeoff documentation

---

src/fastoad/models/performances/mission/mission.py
src/fastoad/models/performances/mission/openmdao/mission.py

This PR fixes several warning messages from mission module:
- deprecation of compute_TOW option (even if not set by user)
- incorrect way of setting values in pandas DataFrames.

Fix warnings

---

src/conftest.py
src/fastoad/_utils/dicts.py
src/fastoad/_utils/tests/test_dicts.py
src/fastoad/constants.py
src/fastoad/module_management/_plugins.py
src/fastoad/module_management/tests/test_plugins.py

When installed from PyPI, Python package names are generally in lower case with hyphens, even if the official package is upper case (e.g. FAST-OAD-CS25).
Nevertheless, when installed in development mode using `pip install .`, the same package can be seen in `pip list` in its original form, that can contain upper case and underscores.
[PEP 426](https://peps.python.org/pep-0426/#name) clearly states that such difference should have no impact :
> All comparisons of distribution names MUST be case insensitive, and MUST consider hyphens and underscores to be equivalent.
Therefore, this PR makes sure that the distribution name of FAST-OAD plugins can be available in lower/upper case with hyphens or underscores without any impact.

Now accepting upper case distribution names for plugins

---

docs/documentation/custom_modules/add_plugin.rst
docs/documentation/usage.rst

A documentation on the commands introduced in PR #477 was forgotten and consequently added here. I propose to put the section on source file generation after the section on the generation of input because this is where source file are first mentionned as a way to "fill" an input file. Additionally a reference to a former section was not working, it should be fixed.

Added documentation for source data file generation

---

docs/documentation/usage.rst
src/fastoad/io/configuration/configuration.py
src/fastoad/io/configuration/resources/configuration.json
src/fastoad/io/configuration/tests/data/valid_sellar.toml
src/fastoad/io/configuration/tests/data/valid_sellar.yml
src/fastoad/io/configuration/tests/data/valid_sellar_alternate.toml
src/fastoad/io/configuration/tests/data/valid_sellar_alternate.yml
src/fastoad/io/configuration/tests/test_configuration.py

This PR allows setting values of options for an OpenMDAO group.
In particular, it will allow using the `auto_order` feature introduced by OpenMDAO 3.28.
As for FAST-OAD modules, options can be set simply by a `<key>: <value>` in the corresponding section.
This is a bit inconsistent with the settings of `linear_solver `and `nonlinear_solver`, that are attributes and not options, and will yet be at the same level in the configuration file. But it looked like it was worth privileging the consistency with the setting of module options.
Documentation has been updated and can be previewed [here](https://fast-oad.readthedocs.io/en/group-options/documentation/usage.html#problem-definition).

Setting group options from configuration file

---

src/fastoad/io/configuration/configuration.py
src/fastoad/openmdao/_utils.py
src/fastoad/openmdao/problem.py
src/fastoad/openmdao/variables/_util.py
tests/integration_tests/oad_process/test_oad_process.py

This PR fixes some performance problems of FAST-OAD.
To get knowledge of the structure of OpenMDAO problems, a setup operation is needed. Until now, due to the several changes that were done separately, this setup operation was done almost each time information was needed, which proved to be CPU costly. 
Here the problem analysis is done in only one place, which allows to reduce to the minimum the number of setup calls. There is still one "additional" setup operation needed to analyze the problem, and possibly another one if dynamically shaped variables are inputs of the problem.
Also, `write_needed_inputs` implementation has been put back in `FASTOADPoblem` (while keeping the `FASTOADProblemConfigurator` method), which allows to spare 2 setup calls when called on the problem instance …

Avoiding unnecessary setup operations

---

src/fastoad/model_base/flight_point.py
src/fastoad/models/performances/mission/base.py
src/fastoad/models/performances/mission/mission.py
src/fastoad/models/performances/mission/openmdao/mission_run.py
src/fastoad/models/performances/mission/segments/base.py
src/fastoad/models/performances/mission/segments/registered/cruise.py
src/fastoad/models/performances/mission/segments/registered/transition.py
src/fastoad/models/performances/mission/segments/time_step_base.py
src/fastoad/models/performances/mission/tests/test_mission.py

This PR simply adds the `consumed_fuel` column in mission csv output file.
This is done by adding this field in FlightPoint class. Though this information is somehow redundant with the `mass` field, it may prove useful to know at each step of the mission the consumed fuel without having to know what was the start mass of the aircraft.

Consumed fuel is now directly computed for each time step

---

src/fastoad/openmdao/tests/openmdao_sellar_example/disc1.py
src/fastoad/openmdao/tests/test_validity_checker.py
src/fastoad/openmdao/validity_checker.py

This PR resolves #509.
As soon as a component was decorated with `ValidityDomainChecker`, it was included in the final check, regardless of the presence of the component in the run problem.
A flag is now added to activate or not the checks by component.

Fix for validity domain checker

---

src/fastoad/models/performances/mission/openmdao/base.py
src/fastoad/models/performances/mission/openmdao/mission.py
src/fastoad/models/performances/mission/openmdao/tests/data/test_mission.xml
src/fastoad/models/performances/mission/openmdao/tests/data/test_mission.yml
src/fastoad/models/performances/mission/openmdao/tests/test_mission.py

Now possible to define a mission that does not contain any route.
In this case, the "specific burned fuel" is not computed, since it is based on range of main route.

Fixed : mission definitions incorrectly had to contain a route

---

src/fastoad/api.py
src/fastoad/io/configuration/resources/configuration.json
src/fastoad/io/configuration/tests/data/conf_sellar_example/disc1.py
src/fastoad/io/configuration/tests/data/valid_sellar.toml
src/fastoad/io/configuration/tests/data/valid_sellar.yml
src/fastoad/io/configuration/tests/data/valid_sellar_alternate.toml
src/fastoad/io/configuration/tests/data/valid_sellar_alternate.yml
src/fastoad/io/configuration/tests/test_configuration.py
src/fastoad/openmdao/base_model_classes.py

This PR adds a base class for groups that contain a NLGS solver.
It is a way to standardize the control of inner solvers through options, making it easy to control all of them at once using `model_options` in configuration file.
This PR also allows having a dict as option value, which is the way solver options will be set from the configuration file.

Base class for cycle groups

---

src/fastoad/cmd/api.py
src/fastoad/io/formatter.py
src/fastoad/io/tests/test_data_file.py
src/fastoad/io/variable_io.py
src/fastoad/io/xml/tests/test_variable_io_base.py
src/fastoad/io/xml/tests/test_variable_io_legacy.py
src/fastoad/io/xml/tests/test_variable_io_standard.py
src/fastoad/io/xml/translator.py
src/fastoad/io/xml/variable_io_base.py
src/fastoad/io/xml/variable_io_standard.py
src/fastoad/openmdao/variables/variable_list.py

Fixes #520 by making the DataFile class able to use `pathlib.Path` instances as input.
Also added some refactoring that CodeClimate was demanding.

Enabling pathlib.Path inputs for DataFile objects

---

src/fastoad/models/performances/mission/segments/registered/altitude_change.py
src/fastoad/models/performances/mission/segments/registered/tests/test_altitude_change.py

In mission, when asking a climb up to an optimal altitude/flight level (i.e. where the maximum CL is achieved), if the maximum CL was achieved for a lower altitude than the starting one, the climb was not stopped until hard limits were attained (the 40000m hard-coded limit, or possibly a crash of the propulsion model).
This PR fixes this problem.

Climb was not stopping when start was already over the asked optimal altitude/flight level

---

docs/documentation/custom_modules/add_modules.rst
docs/documentation/custom_modules/add_variable_documentation.rst
docs/documentation/mission_module/mission_file/setting_values.rst
docs/documentation/usage.rst
docs/documentation/variables.rst
tests/conftest.py

In FAST-OAD documentation, links to OpenMDAO doc were broken. They have been updated using intersphinx mapping.

Fixed links to OpenMDAO doc.

---

src/fastoad/io/configuration/configuration.py
src/fastoad/io/configuration/tests/data/conf_sellar_example/functions.py
src/fastoad/io/configuration/tests/data/ref_inputs.xml
src/fastoad/io/configuration/tests/data/valid_sellar_alternate.toml
src/fastoad/io/configuration/tests/data/valid_sellar_alternate.yml
src/fastoad/io/configuration/tests/test_configuration.py

This PR fixes a bug that was occurring when an option in model_options could add input variables to some component : the generation of the input file was Ok, but the added input variables were not read for problem evaluation.

Fix behavior when model_options could add input variables

---

src/fastoad/openmdao/tests/openmdao_sellar_example/disc1.py
src/fastoad/openmdao/tests/test_validity_checker.py
src/fastoad/openmdao/validity_checker.py

This PR fixes a crash that could occur if `Variable.DomainChecker` was used on a non scalar variable.

Fix validity checker for array variables

---

src/fastoad/gui/analysis_and_plots.py
src/fastoad/gui/tests/data/problem_outputs_updated.xml
src/fastoad/gui/tests/test_analysis_and_plots.py

This is a minor PR to enable to handle a new geometry naming for horizontal tail (`data:geometry:horizontal_tail:root:chord` &#8594; `data:geometry:horizontal_tail:center:chord`) in the plots.
The modification does not affect the compatibility with old naming

Plots now handle horizontal_tail:center new naming

---

src/fastoad/gui/analysis_and_plots.py

This PR should close issue #544 
When using subplots in the mass_breakdown_bar_plot , it was impossible to isolate one aircraft from another and only one plot was masked.
To resolve this ,  we create a grouped legend for each aircraft configuration ( same methods as the one to have the same color for each aircraft)

Adding grouped legend for each aircraft configuration (fix issue #544)

---

CHANGELOG.rst

Draft release : https://github.com/fast-aircraft-design/FAST-OAD/releases/tag/untagged-c4b7b5567d9c0e16b414
Brings compatibility with Python 3.11 and some fixes.

Release v1.7.3

---

src/fastoad/openmdao/exceptions.py
src/fastoad/openmdao/problem.py
src/fastoad/openmdao/tests/data/missing_inputs.xml
src/fastoad/openmdao/tests/openmdao_sellar_example/disc1.py
src/fastoad/openmdao/tests/openmdao_sellar_example/disc2.py
src/fastoad/openmdao/tests/test_problem.py

FAST-OAD behavior was to raise immediately an error if the input file contains a Nan value (for an actually used input variable).
This PR modifies the behavior so an error is raised also when an input variable with a NaN default value is not present in input file.

Better NaN detection in inputs

---

CHANGELOG.rst
src/fastoad/openmdao/validity_checker.py

This PR fixes the incompatibility introduced by OpenMDAO 3.34.
This fix is officialized by a dedicated release: https://github.com/fast-aircraft-design/FAST-OAD/releases/tag/v1.7.4

Release 1.7.4

---

docs/documentation/usage.rst
src/fastoad/io/configuration/configuration.py
src/fastoad/io/configuration/resources/configuration.json
src/fastoad/io/configuration/tests/data/conf_with_imports.yml
src/fastoad/io/configuration/tests/data/to_be_imported/__init__.py
src/fastoad/io/configuration/tests/data/to_be_imported/my_driver_1.py
src/fastoad/io/configuration/tests/data/to_be_imported/my_driver_2.py
src/fastoad/io/configuration/tests/test_configuration.py

This PR proposes a way to specify custom imports in the configuration file and resolves #413.
It assumes the user has in his Python environment the necessary packages.

Custom imports handling in configuration file

---

.github/workflows/tests.yml
src/fastoad/__init__.py
src/fastoad/api.py
src/fastoad/cmd/calc_runner.py
src/fastoad/cmd/tests/data/sellar2.yml
src/fastoad/cmd/tests/test_calc_runner.py
src/fastoad/io/configuration/configuration.py
src/fastoad/io/configuration/tests/data/valid_sellar.toml
src/fastoad/io/configuration/tests/data/valid_sellar.yml
src/fastoad/io/configuration/tests/test_configuration.py
src/fastoad/openmdao/problem.py
tests/integration_tests/oad_process/data/mission_definition/sizing_breguet.yml
tests/integration_tests/oad_process/data/oad_process.yml
tests/integration_tests/oad_process/test_oad_process.py

This PR adds the CalcRunner class:
- it allows to "make local" FAST-OAD computations, i.e. put in one folder all input and output files, making it possible to run again the computation with only this folder (configuration file is modified accordingly)
- it allows to run a batch of these "localized" computations concurrently, using either `multiprocessing` or `mpi4py`.
The follow-up of this PR will be:
- Making this feature available from CLI
- Refining the continuation of batch, based on calc results instead of simply the existence of the calc folder (based on calc number)
In a second time, adding a way of building the computation inputs (i.e a DoE) will be useful.

Added a feature for concurrently running several computations

---

src/fastoad/models/performances/mission/openmdao/mission_wrapper.py
src/fastoad/models/performances/mission/openmdao/tests/data/test_payload_range.yml

Resolves #561.
Asking for `self.mission_name property` too soon was a problem.

Payload range module can now handles mission files with several mission

---

pyproject.toml
src/fastoad/cmd/calc_runner.py
src/fastoad/cmd/tests/data/inputs_alt.xml
src/fastoad/cmd/tests/test_calc_runner.py

This PR is a follow-up of #554 and fixes some problems with CalcRunner class:
- computations could not run if a relative path was given for `input_file_path`
- input file was not modified for computations that were isolated in a local folder

Fix CalcRunner

---

src/fastoad/model_base/flight_point.py
src/fastoad/model_base/propulsion.py
src/fastoad/models/performances/mission/mission_definition/mission_builder/mission_builder.py
src/fastoad/models/performances/mission/openmdao/mission_run.py
src/fastoad/models/performances/mission/openmdao/mission_wrapper.py
src/fastoad/models/performances/mission/segments/time_step_base.py
src/fastoad/models/performances/mission/tests/test_routes.py

This PR does some adjustments to mission module.
In particular, it rationalizes a bit the "scalarize" operation.
It also fixes the status of FlightPoint.ground_distance (`is_cumulative` is True).
Another (very) minor fix is that, in description of variables related to phases outside routes, this phases were qualified as routes.

Cleaning up code in mission module

---

src/fastoad/models/performances/mission/mission_definition/mission_builder/mission_builder.py
src/fastoad/models/performances/mission/openmdao/resources/sizing_mission.yml

Since FAST-OAD 1.4.0, the mission definition file can describe the whole mission, including the phases before reaching the "input weight", i.e. takeoff mass (TOW), generally. The point is to have a target mass in the definition, by adding a mass_input segment in the proper phase:
```yaml
- segment: mass_input
target:
mass: ~~TOW
```

Automated addition of taxi-out and takeoff phases is now deprecated.

---

src/fastoad/models/performances/mission/segments/registered/altitude_change.py
src/fastoad/models/performances/mission/segments/registered/cruise.py
src/fastoad/models/performances/mission/segments/registered/hold.py
src/fastoad/models/performances/mission/segments/registered/speed_change.py
src/fastoad/models/performances/mission/segments/registered/takeoff/end_of_takeoff.py
src/fastoad/models/performances/mission/segments/registered/taxi.py
src/fastoad/models/performances/mission/segments/registered/tests/test_hold.py
src/fastoad/models/performances/mission/segments/time_step_base.py

This PR addresses 2 small problems:
- lift value was generally not computed (knowing CL can be enough), though the column is always in csv files.
- in ClimbAndCruise segment, the target of inner climb segment could be set without guarantee the climb segment was not None.
Additionally, some refactoring has been done to have CL and CD computed in only one location. For this purpose, abstract classes `AbstractLiftFromWeightSegment` and `AbstractLiftFromAoASegment` have been created, in the same purpose as `AbstractManualThrustSegment` and `AbstractRegulatedThrustSegment`.
BTW, the `load_factor` attribute has been added to `AbstractLiftFromWeightSegment`. It's an easy addition that allows to simulate segments with load factors different from 1.

Minor fixes in mission module

---

docs/documentation/mission_module/mission_file/segments.rst
src/fastoad/models/performances/mission/segments/registered/tests/test_transition.py
src/fastoad/models/performances/mission/segments/registered/transition.py

This PR allows to simulate a mass loss that is not linked to fuel consumption.
Documentation preview: https://fast-oad.readthedocs.io/en/delta-payload-in-segment-transition/documentation/mission_module/mission_file/segments.html#mass-loss-without-fuel-consumption

Mission module: transition segment can now handle a payload decrease

---

src/fastoad/model_base/datacls.py
src/fastoad/models/performances/mission/segments/registered/cruise.py
src/fastoad/models/performances/mission/segments/registered/tests/conftest.py
src/fastoad/models/performances/mission/segments/registered/tests/test_cruise.py

This modification allows the use of non pickable object as propulsion component in the mission.
This is a rather rare error but can happen with surrogate models using compiled code (for example when using GPX from the smt library). The error was essentially due to the function `deepcopy` that requires all object to be pickable. Two modifications were made to bypass the use of `deepcopy` without affecting the behaviour of the code.
For what it is worth, time execution of 1000 instanciation of ClimbAndCruiseSegment averaged over 5 repeatition: legacy code 2.539s, with new code: 2.133s

Allow non pickable object as propulsion component

---

src/fastoad/openmdao/tests/test_variables.py
src/fastoad/openmdao/variables/variable.py

Fixed the consistency of the `get_val` method. This PR introduces a small breaking change: previously, if the FAST-OAD output was a 1D iterable (i.e., a scalar), `get_val` would return an iterable, while requesting the same value with unit conversion would return a scalar. This inconsistency has been fixed, so it is no longer necessary to do `prob.get_val("var_name")[0]` to extract the scalar value. If the exact raw value from the FAST-OAD output is needed, it can still be accessed using `prob["var_name"]`.
closes #606

Fix inconsistent behaviour of the get_val method when not providing units of measure

---

.gitignore
src/fastoad/testing.py

When using the `run_system` metod to perform tests, the default solver of the `BaseCycleGroup` class is used which is `NonlinearBlockGS`. This means that all component tested using this method are ran at least twice (enough for the solver to consider it is done) even if there is no point in doing it. This commit change the default to NonLinearRunOnce which is used unless specified otherwise.
Tests for the CS25 repo have been ran using the fast-oad-core version on this branch and all tests still pass.
Additionally, the files generated by the OpenMDAO reports have been added to the .gitgnore
Closes #623

Add RunOnce solver as default for `run_system`
