fast-aircraft-design/FAST-OAD

- .codacy.yml
- .github/workflows/tests.yml
- README.md
This PR links the GitHub repo to Codacy for code quality check and Codecov for coverage report
> Code tools

- CHANGELOG.rst
- README.md
- docs/documentation/install.rst
- docs/documentation/overview.rst
- docs/index.rst
- docs/refs.bib
- head page has been completed
- unused bibtex references have been removed
- changelog has been updated
> Updated documentation

- src/fastoad/cmd/api.py
- src/fastoad/cmd/resources/fastoad.toml
- src/fastoad/io/configuration/__init__.py
- src/fastoad/io/configuration/configuration.py
- src/fastoad/io/configuration/exceptions.py
- src/fastoad/io/configuration/tests/data/missing_input_file.toml
- src/fastoad/io/configuration/tests/data/missing_model.toml
- src/fastoad/io/configuration/tests/data/missing_output_file.toml
- src/fastoad/io/configuration/tests/data/valid_sellar.toml
- src/fastoad/io/configuration/tests/test_configuration.py
- src/fastoad/io/xml/variable_io_base.py
- src/fastoad/models/weight/cg/cg_components/update_mlg.py
- src/fastoad/openmdao/problem.py
- src/fastoad/utils/files.py
- src/fastoad/utils/postprocessing/optimization_viewer.py
- src/fastoad/utils/postprocessing/tests/data/valid_sellar.toml
- src/fastoad/utils/postprocessing/tests/test_optimization_viewer.py
- src/fastoad/utils/resource_management/copy.py
- tests/integration_tests/oad_process/test_oad_process.py
This PR separates FASTOADProblem in FASTOADProblem + FASTOADProblemConfigurator
FASTOADProblemConfigurator instance reads and manipulates the configuration file. Then it can create a FASTOADProblem instance that can be manipulated afterward like a pure OpenMDAO Problem instance.
Also fixes a bug on auto_scaling feature: it was crashing if upper bound was 0 and lower bound was undefined => auto_scaling is now used only if upper and lower are defined.
Additionally, user-defined scaling are no more ignored if auto_scaling is True.
> Refactoring of FASTOADProblem

- .github/workflows/tests.yml
- docs/index.rst
Looks like cache got corrupted again
Let's see what happens when caching Poetry cache... 😞
Also made minor changes in doc
> GitHub workflow fix

- .github/workflows/tests.yml
- README.md
Now using version 2 of GitHub cache action 
Added some badges to README file (allowed a test commit for seeing cache usage)
> Update cache action

- poetry.lock
- pyproject.toml
because of incompatibility with 3.1.1.
> OpenMDAO version is now limited up to 3.1.0 

- src/fastoad/cmd/api.py
- src/fastoad/io/xml/constants.py
- src/fastoad/io/xml/variable_io_base.py
- src/fastoad/openmdao/problem.py
- src/fastoad/openmdao/tests/test_variables.py
- src/fastoad/openmdao/variables.py
- src/fastoad/utils/postprocessing/tests/data/light_data.xml
- src/fastoad/utils/postprocessing/tests/test_variable_viewer.py
- src/fastoad/utils/postprocessing/variable_viewer.py
This PR provides the  possibility to select inputs or outputs in the VariableViewer.
For that:
- An io attribute was added to variables ("IN" or "OUT")
- The VariableViewer UI was updated to provide the selector as a dropdown menu
To determine the type of variable ("IN" or "OUT") when reading a Problem, it must be well posed and hence have no unconnected inputs (no missing IndepVarComp).
> Input output selector

- CHANGELOG.rst
> Updated change log

- .github/workflows/tests.yml
- .github/workflows/watchman_tests.yml
- docs/documentation/add_modules.rst
- poetry.lock
- src/fastoad/models/performances/breguet.py
- src/fastoad/openmdao/resources/variable_descriptions.txt
Resolves #188.
Project dependencies have been updated: cache of GitHub workflow got corrupted, so this was the occasion to do an update.
> Constants in Breguet computation are converted to OpenMDAO variables

- CHANGELOG.rst
- README.md
- docs/documentation/add_modules.rst
- docs/documentation/install.rst
Updated documentation and prepared v0.4.0-beta draft release.
> v0.4.0-beta release

- CHANGELOG.rst
- poetry.lock
- pyproject.toml
- src/fastoad/models/performances/breguet.py
- src/fastoad/models/performances/tests/test_breguet.py
- Dependency modification to take into account problems with OpenMDAO 3.2
- Small fix in Breguet module, outputs for climb/descent distances were incorrect
- Release 0.4.1-beta is drafted
> Release 0.4.1 beta

- CHANGELOG.rst
Preparation of release 0.5.0-beta
draft release here:
https://github.com/fast-aircraft-design/FAST-OAD/releases/tag/untagged-0b18eb30bc6032bd3a33
> Release 0.5.0-beta

- src/fastoad/cmd/api.py
Small PR just to add the computation time info when running `evaluate_problem` and `optimize_problem`
> Added computation time to logging info

- CHANGELOG.rst
A new release is proposed:
https://github.com/fast-aircraft-design/FAST-OAD/releases/tag/untagged-7eb1e63b8e310dd32f4c
> Release 0.5.2 beta

- src/fastoad/cmd/api.py
- src/fastoad/cmd/tests/data/short_inputs.xml
- src/fastoad/cmd/tests/test_api.py
- src/fastoad/notebooks/tutorial/01_tutorial.ipynb
This PR aims at making the call of the `VariableViewer` simpler, especially in notebooks, by adding it to the api:
`api.variable_viewer(DATA_FILE)`
Closes #217
> Issues 217 variable viewer api

- src/fastoad/models/performances/mission/segments/speed_change.py
- src/fastoad/models/performances/mission/segments/tests/test_segments.py
> Mach number can be used as target for SpeedChangeSegment.

- src/fastoad/models/weight/cg/cg_components/compute_cg_loadcase1.py
- src/fastoad/models/weight/cg/cg_components/compute_cg_loadcase2.py
- src/fastoad/models/weight/cg/cg_components/compute_cg_loadcase3.py
- src/fastoad/models/weight/cg/cg_components/compute_cg_loadcase4.py
- src/fastoad/models/weight/cg/cg_components/compute_cg_ratio_aft.py
> Changed units of data:weight:aircraft_empty:mass from "m" to "kg".

- src/fastoad/utils/postprocessing/analysis_and_plots.py
This small PR modifies how mass breakdown plots are achieved in order to be more generic for applications that do not use as detailed mass breakdown as FAST-OAD. Thank you @areysset!
> More generic mass breakdown plot

- src/fastoad/cmd/api.py
- src/fastoad/cmd/tests/test_api.py
> Now api.generate_inputs() returns the path of generated file.

- src/fastoad/cmd/api.py
- src/fastoad/io/configuration/configuration.py
- src/fastoad/io/tests/__init__.py
- src/fastoad/io/tests/test_data_file.py
- src/fastoad/io/variable_io.py
- src/fastoad/models/performances/mission/openmdao/tests/test_mission.py
- src/fastoad/notebooks/01_tutorial/01_tutorial.ipynb
- src/fastoad/openmdao/tests/test_variables.py
- src/fastoad/openmdao/variables.py
- tests/integration_tests/oad_process/test_oad_process.py
This PR resolves #195.
It proposes a simple DataFile class that loads FAST-OAD data files and allows direct access to variables as in the VariableList class.
This class is used in tutorial notebook to modify range through Python for the second MDA.
> Issue 195 variable file

- src/fastoad/notebooks/02_CeRAS_case_study/ceras_utils.py
Expected CSV column names in ceras_utils.py have changed.
> Mission plots in CeRAS tutorial had not been updated after CSV change 

- docs/citation.rst
- docs/conf.py
- docs/documentation/usage.rst
- docs/index.rst
This PR updates the documentation with the new fastoad.yml template. It also add a citation section describing the standard way to cite this work. 
Updated doc after RTD build [here](https://fast-oad.readthedocs.io/en/updated_doc/)
> Updated doc

- .codacy.yml
- docs/documentation/custom_modules/add_modules.rst
- docs/documentation/custom_modules/add_propulsion_module.rst
- pyproject.toml
- src/fastoad/api.py
- src/fastoad/notebooks/01_tutorial/01_tutorial.ipynb
- src/fastoad/notebooks/01_tutorial/02_postprocessing.ipynb
- src/fastoad/notebooks/02_CeRAS_case_study/CeRAS_case_study.ipynb
- tests/integration_tests/oad_process/test_oad_process.py
This PR creates a fastoad/api.py file with key FAST-OAD features, that can be imported with `import fastoad.api as oad`.
Also, a new name (`fast-oad`) is added for the command line, that is just an alias of `fastoad`.
> Api definition

- CHANGELOG.rst
- README.md
- docs/documentation/custom_modules/add_modules.rst
- docs/index.rst
- src/fastoad/notebooks/01_tutorial/02_postprocessing.ipynb
- src/fastoad/notebooks/01_tutorial/data/oad_process_timestep_mission.yml
draft release here:
https://github.com/fast-aircraft-design/FAST-OAD/releases/tag/untagged-c55bf782345aef05dad7
Updated RTD doc: https://fast-oad.readthedocs.io/en/release-1.0.0/
> Release 1.0

- src/fastoad/gui/variable_viewer.py
This PR corrects a bug where the variable viewer displays a sheet at each interaction with the tool bar.
Fixes #301.
> Corrected bug in variable viewer

- CHANGELOG.rst
- src/fastoad/io/configuration/configuration.py
I propose to release a minor update to integrate the fix for #301 and also to fix #304 in the same row.
Draft release here: https://github.com/fast-aircraft-design/FAST-OAD/releases/tag/untagged-5e4fadb65fb0aae2bc6e
> Release v1.0.1

- src/fastoad/gui/analysis_and_plots.py
- src/fastoad/gui/optimization_viewer.py
- src/fastoad/gui/variable_viewer.py
A bit of cleaning of the GUI-related code (Codacy is very happy) and a different solution to #301.
This was also a way for me to think about this part of the code. As it will probably grow or be extended soon, it may benefit some refactoring (e.g. with a dedicated class for each GUI element).
Also, some features might be thought over:
- should the optimization viewer be allowed to modify output values ?
- should we provide a "load" button with a file selection dialog ?
- shouldn't the current "load" button be named "reload" ?
- should it trigger a confirmation dialog, since we do not provide "undo" ?
- should the "save" button trigger a confirmation dialog, since we do not provide "undo" ?
- should we provide "undo" ?
> Gui linting

- CHANGELOG.rst
New minor release
Draft release here:
https://github.com/fast-aircraft-design/FAST-OAD/releases/tag/untagged-1425c6c2490c5c8e4a63
> Release v1.0.3

- src/fastoad/notebooks/02_CeRAS_case_study/CeRAS_case_study.ipynb
> Fixed some wrong file links and typos in CeRAS notebook

- src/fastoad/_utils/testing.py
- src/fastoad/models/performances/mission/openmdao/mission.py
Fixed some deprecation warnings.
> Fix deprecations

- CHANGELOG.rst
- docs/index.rst
Draft release: https://github.com/fast-aircraft-design/FAST-OAD/releases/tag/untagged-edcb9e75a6e7437de484
> Release v1.3.3

- CHANGELOG.rst
Draft release here: https://github.com/fast-aircraft-design/FAST-OAD/releases/tag/untagged-cbcc84004db0e6d1dfb3
> Release v1.3.4

- CHANGELOG.rst
Draft release: https://github.com/fast-aircraft-design/FAST-OAD/releases/tag/untagged-31ccdf9a6a87dae6c688
> Release v1.3.5

- .github/workflows/tests.yml
- CHANGELOG.rst
- poetry.lock
- pyproject.toml
- release/pyproject.toml
draft release: https://github.com/fast-aircraft-design/FAST-OAD/releases/tag/untagged-cf0620cadb34b594e426
_Note: the concerned branch leaves apart developments of #467 and cherry-picks last commits of master branch to "include" #475 (not the ideal solution, but it will do for this time)._
> Release v1.4.2

- src/fastoad/openmdao/tests/test_variables.py
- src/fastoad/openmdao/variables/variable.py
- src/fastoad/openmdao/variables/variable_list.py
This PR closes #472 by adding the possibility to have variables with value of type string. This is particularly useful when using discrete variables to store information for displaying of computation logics.
> Issue 472 variable viewer with values of type string

- src/fastoad/model_base/flight_point.py
- src/fastoad/models/performances/mission/polar.py
- src/fastoad/models/performances/mission/polar_modifier.py
- src/fastoad/models/performances/mission/segments/base.py
- src/fastoad/models/performances/mission/segments/end_of_takeoff.py
- src/fastoad/models/performances/mission/segments/ground_speed_change.py
- src/fastoad/models/performances/mission/segments/rotation.py
- src/fastoad/models/performances/mission/segments/tests/test_takeoff_segments.py
This is a separate pull request to include only dedicated takeoff segments and polar modifier. The changes to mission builder will be added separately.
> Added only takeoff segments and polar.

- src/fastoad/models/performances/mission/openmdao/tests/test_with_custom_segment.py
- src/fastoad/models/performances/mission/segments/__init__.py
- src/fastoad/models/performances/mission/segments/base.py
- src/fastoad/models/performances/mission/segments/cruise.py
- src/fastoad/models/performances/mission/segments/takeoff/__init__.py
- src/fastoad/models/performances/mission/segments/takeoff/end_of_takeoff.py
- src/fastoad/models/performances/mission/segments/takeoff/rotation.py
- src/fastoad/models/performances/mission/segments/takeoff/takeoff.py
- src/fastoad/models/performances/mission/segments/taxi.py
- src/fastoad/models/performances/mission/segments/tests/test_takeoff_segments.py
This PR allows to make any implemented flight part usable as segment in mission files.
A Takeoff super-segment is added, which is a combination of the 3 "atomic" takeoff segments (ground speed acceleration, rotation, end of takeoff).
> "Super" segment

- src/fastoad/openmdao/variables/variable_list.py
This PR brings back compatibility with future versions of OpenMDAO (> 3.25)
> Fixed VariableList.from_ivc()

- src/fastoad/io/tests/test_data_file.py
- src/fastoad/openmdao/variables/_util.py
- src/fastoad/openmdao/variables/variable_list.py
This PR fixes #421.
It also enhances a bit the dreadful `VariableList.from_problem()` method by putting it outside of `VariableList` class and cutting it into more meaningful pieces (hopefully).
> Fix datafile

- src/fastoad/models/performances/mission/segments/time_step_base.py
This PR is a simple follow-up to #497.
It applies the same fix, while making it more robust (hopefully).
> Enhanced fix for climb segment going far too high when asked for optimal altitude in some cases

- CHANGELOG.rst
Draft release : https://github.com/fast-aircraft-design/FAST-OAD/releases/tag/untagged-9ca10b3362e506c94443
> Release v1.5.2

- CHANGELOG.rst
Draft release [here](https://github.com/fast-aircraft-design/FAST-OAD/releases/tag/untagged-53d6b6c5fe4fd9474037).
> Release v1.6.0

- CHANGELOG.rst
Draft release: https://github.com/fast-aircraft-design/FAST-OAD/releases/tag/untagged-88951a6a770ecd34e7e2
> Release v1.7.0

- src/fastoad/models/performances/mission/openmdao/tests/test_mission.py
- src/fastoad/models/performances/mission/openmdao/tests/test_mission_run.py
- src/fastoad/models/performances/mission/openmdao/tests/test_mission_takeoff.py
- src/fastoad/models/performances/mission/openmdao/tests/test_payload_range.py
- src/fastoad/models/performances/mission/openmdao/tests/test_sizing_breguet.py
- src/fastoad/models/performances/mission/openmdao/tests/test_sizing_mission.py
- src/fastoad/models/performances/mission/openmdao/tests/test_with_custom_segment.py
- src/fastoad/openmdao/variables/variable_list.py
- src/fastoad/testing.py
This PR moves the run_system() test utility in public API.
> run_system() utility in public API

- CHANGELOG.rst
https://github.com/fast-aircraft-design/FAST-OAD/releases/tag/v1.7.2
> Release v1.7.2

- src/fastoad/gui/analysis_and_plots.py
This PR reorders a bit the plotting function for sunburst mass breakdown.
Hopefully, it will make it a bit more readable (until a future complete rewriting...).
> Refactored sunburst mass breakdown plot.

- src/fastoad/io/configuration/tests/data/ref_inputs.xml
- src/fastoad/openmdao/problem.py
- src/fastoad/openmdao/tests/data/ref_inputs_outputs.xml
- src/fastoad/openmdao/tests/openmdao_sellar_example/disc2.py
- src/fastoad/openmdao/tests/test_problem.py
This PR modifies the input reading process so that values of output variables, if present in input file, are also set before computation.
In some cases, it might speed up the convergence (Sellar problem is solved in 2 iterations).
> Using output values in input file

- CHANGELOG.rst
- src/fastoad/model_base/flight_point.py
- src/fastoad/model_base/tests/test_flight_point.py
Draft release : https://github.com/fast-aircraft-design/FAST-OAD/releases/tag/untagged-15ce0b74d127822a97f2
> Release v1.8.0

- CHANGELOG.rst
- poetry.lock
Release: https://github.com/fast-aircraft-design/FAST-OAD/releases/tag/v1.8.1
> Release v1.8.1

- CHANGELOG.rst
draft release: https://github.com/fast-aircraft-design/FAST-OAD/releases/tag/untagged-8dcb140630fd139b88a7
> Release v1.8.2

- .github/PULL_REQUEST_TEMPLATE.md
We add here a template for the Pull Requests (showed actually by this PR). This will make it easier for maintainers to review contributions and ensure consistency across all PRs.
Closes #584
> New github Pull Request template

- docs/_static/custom_admonitions.css
- docs/conf.py
- docs/directives/segment_attributes.py
- docs/documentation/mission_module/mission_file/mission_file.rst
- docs/documentation/mission_module/mission_file/segments.rst
- src/fastoad/models/performances/mission/base.py
- src/fastoad/models/performances/mission/mission_definition/mission_builder/tests/test_mission_builder.py
- src/fastoad/models/performances/mission/openmdao/tests/test_with_custom_segment.py
This PR allows to better link mission segments and their parameters in the segment documentation.
Preview here: https://fast-oad.readthedocs.io/en/mission-doc-update/documentation/mission_module/mission_file/segments.html
> Enhanced documentation for mission segment parameters

- .github/workflows/tests.yml
- .github/workflows/watchman_tests.yml
Added a timeout for tests and watchman tests to avoid improper usage of resources.
Closes #604
> Set a timeout limit on GitHub Action's pipeline

- CHANGELOG.rst
draft release: https://github.com/fast-aircraft-design/FAST-OAD/releases/edit/untagged-8605e661f6ee49641117
> Release v1.8.3

- src/fastoad/models/performances/mission/segments/registered/tests/test_takeoff_segments.py
- src/fastoad/models/performances/mission/segments/time_step_base.py
This PR addresses the problem described by #597.
The base time-step algorithm finds the exact time at which the target is reached with a tolerance of 1e-5 (absolute tolerance). It does so using a Newton method that iterates over the time step until the distance to target reaches 0. The Newton method is however not precise enough to reach the tolerance of 1e-5. So it is located within a while loop that gradually decreases the tolerance of the Newton solver. This is still not general enough and can lead to mission being stuck in the while loop.
The changes consist of:
- Modifying an existing test to enter the never ending while loop. The test fails if timed-out.
- Normalising the distance to target with the last_point_to_target
- Getting rid of the while loop
Closes issue #597.
No new …
> Fix mission target calculation
